# Generated by Django 5.2.4 on 2025-07-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbooks',
            old_name='classes',
            new_name='class_name',
        ),
    ]
