# Generated by Django 5.2.4 on 2025-07-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
