# Generated by Django 5.2.4 on 2025-07-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('classes', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='TextBook/images/')),
                ('book', models.FileField(blank=True, null=True, upload_to='TextBook/books/')),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text_kg',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text_kz',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text_tr',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text_uz',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_kg',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_kz',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_kg',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_kz',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_tr',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_uz',
        ),
    ]
